#!/usr/bin/env bash

# uname logic cribbed from https://github.com/microsoft/WSL/issues/4071#issuecomment-1223393940
# op env vars idea from
# * https://www.1password.community/discussions/developers/is-it-possible-for-1password-cli-running-on-wsl-to-connect-with-1password-hosted/93181/replies/93217
# * https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/

unameOut=$(uname -a)
case "${unameOut}" in
  *Microsoft*) OS="WSL";; #wls must be first since it will have Linux in the name too
  *microsoft*) OS="WSL2";;
  Linux*)      OS="Linux";;
  Darwin*)     OS="Mac";;
  CYGWIN*)     OS="Cygwin";;
  MINGW*)      OS="Windows";;
  *Msys)       OS="Windows";;
  *)           OS="UNKNOWN:${unameOut}"
esac

if [[ "${OS}" == "Mac" ]] && sysctl -n machdep.cpu.brand_string | grep -q 'Apple M1'; then
  #Check if its an M1. This check should work even if the current processes is running under x86 emulation.
  OS="MacM1"
fi

# Get the name of the binary being executed
BINARY_NAME=$(basename "$0")

if [[ "${OS}" == "WSL"* ]]; then
  case "$BINARY_NAME" in
  # Pass OP_* env vars up from WSL to Windows host when running op
  op)
    mapfile -d '' op_env_vars < <(env -0 | grep -z ^OP_ | cut -z -d= -f1)
    WSLENV_VALUE="${WSLENV:-}:$(
      IFS=:
      echo "${op_env_vars[@]}"
    )"
    export WSLENV="$WSLENV_VALUE"
    ;;
  esac
  BINARY_NAME="${BINARY_NAME}.exe"
fi

case "$BINARY_NAME" in
  tailscale)
    if [[ "${OS}" == "Mac"* ]]; then
      BINARY_NAME="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
    fi
    ;;
  *)
esac

exec "$BINARY_NAME" "$@"
