#!/usr/bin/env bash
set -euo pipefail

query="$1"
command="$2"

KNIFE="knife"
PSSH="pssh"

if hash k 2>/dev/null; then
  KNIFE="k"
fi

if hash parallel-ssh 2>/dev/null; then
  PSSH="parallel-ssh"
fi


hosts="$($KNIFE search "$query" -Fj -a fqdn | jq -r '.rows[][].fqdn' | tr '\n' ' ')"

"$PSSH" -P -H "$hosts" "$command"

exit 0
