#!/bin/sh
ip="$(aws ec2 describe-instances --instance-id "$1" | jq -r '.Reservations[].Instances[].PrivateIpAddress')"
echo "$ip" | egrep -q '([0-9]\.){1,3}[0-9]{1,3}'
if [ $? != 0 ]; then
  echo "Can't determine private IP; aborting" >2
  exit 1
fi
shift
ssh "$ip" "$@"
