#!/usr/bin/env bash
###############################################################################
# ABOUT
#   Diffs terraform plan output in vscode. Useful in cases where terraform's
#   concise plan output is hiding details you care about.
#
# USAGE
#   Use similarily to how you'd run "terraform plan".
#   Extra args are passed to plan:
#     tfdiff -target='module.some_module'
#
# REQUIRES
#   terraform
#   jq
#   code (vscode)
###############################################################################
set -euo pipefail
export IFS=$'\n\t'

tmpdir="$(mktemp -d)"
trap 'rm -rfv $tmpdir' EXIT

export TF_IN_AUTOMATION=1
(
  terraform plan -out "$tmpdir/tfplan" "$*" >/dev/null
  terraform show -json "$tmpdir/tfplan" | jq '.resource_changes[] | select(.change.actions as $actions | "no-op" | IN($actions[]) | not) | [.change.before]' > "$tmpdir/before.json"
  terraform show -json "$tmpdir/tfplan" | jq '.resource_changes[] | select(.change.actions as $actions | "no-op" | IN($actions[]) | not) | [.change.after]' > "$tmpdir/after.json"
  code --wait --diff "$tmpdir/before.json" "$tmpdir/after.json"
)
