#!/usr/bin/env bash
set -euo pipefail
youtube-dl --audio-quality 0 --extract-audio --audio-format mp3 "$1" -o "$HOME/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/%(title)s.%(ext)s"
